### ISSUE TITLE
Dowhy CausalModel does not have 'causal_estimator' attribute

### ISSUE THREAD

**Issue by Lyutenant** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#3]
Both chapter 9 and chapter 10 notebooks have code like `effect_pred = model.causal_estimator.effect()`.
I got an error running them: **AttributeError: 'CausalModel' object has no attribute 'causal_estimator'**

The book states that it uses DoWhy 0.8 but I am currently using DoWhy 0.10.1 (just want to keep my learning experience up-to-date) but I cannot determine if that's the cause of it. If it is, then how to implement the model on test dataset with current version of DoWhy? If not, then what have I missed?

Thanks!

**Comment by AlxndrMlk** [comment]
Hi @Lyutenant - thank you for raising this up.

You are correct, there were some changes in the DoWhy's API since version 0.9+ and `.causal_estimator` object has been removed from the `CausalModel` class.

There are two ways of generating predictions on new data using the new API (examples follow the Chapter 09 notebook, S-Learner section):

1. Accessing the fitted estimator from the `estimate` object:

```python
estimate._estimator_object.effect(earnings_interaction_test.drop(['true_effect', 'took_a_course'], axis=1))
```

2. Passing new data to the `target_units` parameter while setting `fit_estimator` to `False`:
```python
model.estimate_effect(
    identified_estimand=estimand,
    method_name='backdoor.econml.metalearners.SLearner',
    fit_estimator=False,
    target_units=earnings_interaction_test.drop(['true_effect', 'took_a_course'], axis=1),
).cate_estimates
```

I personally find the second way somehow less intuitive and less clear than the first one. 

I also want to share with you that I encountered some unexpected behaviors in version 0.10.1 when using these methods. I raised an issue with the DoWhy team here: https://github.com/py-why/dowhy/issues/1038


If you asked my opinion, I'd recommend that you stick with DoWhy 0.8 at least for now.

I hope this reply will be helpful to you.

Wish you a joyful journey with the book and happy causal learning!

**Comment by Lyutenant** [comment]
Hi @AlxndrMlk , thanks for your prompt reply. 
I switched back to dowhy 0.8 and the issue is gone. I am taking your advice to stick to 0.8 for now, at least until the issue you have raised with the DoWhy team is solved.

p.s. I do enjoy your book a lot!
